// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/ucladevx/BPool/models"

import stores "github.com/ucladevx/BPool/stores"

// PassengerStore is an autogenerated mock type for the PassengerStore type
type PassengerStore struct {
	mock.Mock
}

// Count provides a mock function with given fields: clauses
func (_m *PassengerStore) Count(clauses []stores.QueryModifier) (int, error) {
	ret := _m.Called(clauses)

	var r0 int
	if rf, ok := ret.Get(0).(func([]stores.QueryModifier) int); ok {
		r0 = rf(clauses)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]stores.QueryModifier) error); ok {
		r1 = rf(clauses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *PassengerStore) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: lastID, limit
func (_m *PassengerStore) GetAll(lastID string, limit int) ([]*models.Passenger, error) {
	ret := _m.Called(lastID, limit)

	var r0 []*models.Passenger
	if rf, ok := ret.Get(0).(func(string, int) []*models.Passenger); ok {
		r0 = rf(lastID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Passenger)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(lastID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *PassengerStore) GetByID(id string) (*models.Passenger, error) {
	ret := _m.Called(id)

	var r0 *models.Passenger
	if rf, ok := ret.Get(0).(func(string) *models.Passenger); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Passenger)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ride
func (_m *PassengerStore) Insert(ride *models.Passenger) error {
	ret := _m.Called(ride)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Passenger) error); ok {
		r0 = rf(ride)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ride
func (_m *PassengerStore) Update(ride *models.Passenger) error {
	ret := _m.Called(ride)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Passenger) error); ok {
		r0 = rf(ride)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WhereMany provides a mock function with given fields: clauses
func (_m *PassengerStore) WhereMany(clauses []stores.QueryModifier) ([]*models.Passenger, error) {
	ret := _m.Called(clauses)

	var r0 []*models.Passenger
	if rf, ok := ret.Get(0).(func([]stores.QueryModifier) []*models.Passenger); ok {
		r0 = rf(clauses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Passenger)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]stores.QueryModifier) error); ok {
		r1 = rf(clauses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
